development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: portfolio_development
  pool: 5
  username: JPotter
  password:
  port: 5432

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: portfolio_test
  pool: 5
  username: JPotter
  password:
  port: 5432